version: '3.8'

services:
  ai-analyst-demo:
    build: .
    ports:
      - "8501:8501"  # Streamlit Web界面
      - "8000:8000"  # REST API服务
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    volumes:
      - ./google.campaign_daily_geo_stats.csv:/app/google.campaign_daily_geo_stats.csv:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health && curl -f http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-analyst-demo
    restart: unless-stopped